import "dotenv/config";
import express from "express";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import { fileURLToPath } from "url";
import { jwtVerify, createRemoteJWKSet, SignJWT, importPKCS8 } from "jose";

/* =====================================================
   PATHS / APP
===================================================== */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

// LTI launches commonly POST as form-urlencoded
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// Static files (includes public/jwks.json generated by scripts/generate-jwks.mjs)
app.use(express.static(path.join(__dirname, "public"), { maxAge: "1h" }));

/* =====================================================
   ENV
===================================================== */
const PORT = process.env.PORT || 3000;

// Tool registration in Learn (LTI)
const CLIENT_ID = must("CLIENT_ID"); // from Learn tool provider (Client ID)
const LEARN_HOST = must("LEARN_HOST"); // e.g. mapua-test.blackboard.com

// Your tool base URL (Render)
const TOOL_BASE_URL = must("TOOL_BASE_URL"); // e.g. https://uef-integ-final.onrender.com
const REDIRECT_URI = must("REDIRECT_URI"); // e.g. https://uef-integ-final.onrender.com/launch

// Platform (Anthology) endpoints (from developer portal / Learn config)
const PLATFORM_ISSUER = must("PLATFORM_ISSUER"); // usually https://blackboard.com
const PLATFORM_JWKS_URL = must("PLATFORM_JWKS_URL"); // https://developer.anthology.com/.well-known/jwks.json
const PLATFORM_OIDC_AUTH_ENDPOINT = must("PLATFORM_OIDC_AUTH_ENDPOINT"); // .../oidcauth
const PLATFORM_OAUTH_TOKEN_ENDPOINT = must("PLATFORM_OAUTH_TOKEN_ENDPOINT"); // .../oauth2/jwttoken

// REST key/secret (Learn REST integration) — optional until you call REST APIs
const REST_KEY = process.env.REST_KEY || "";
const REST_SECRET = process.env.REST_SECRET || "";

// Your NF widget script URL OR hosted widget page (choose one for UEF injection)
const NF_WIDGET_SRC = process.env.NF_WIDGET_SRC || "";
// Example you pasted:
// https://portalapi.noodlefactory.ai/api/v1/widget/widget-sdk/A60CF5EFD2705979/widget.js

/* =====================================================
   HELPERS
===================================================== */
function must(key) {
  const v = process.env[key];
  if (!v) throw new Error(`Missing env: ${key}`);
  return v;
}

function escapeHtml(str = "") {
  return String(str)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function base64url(bytes) {
  return Buffer.from(bytes)
    .toString("base64")
    .replaceAll("+", "-")
    .replaceAll("/", "_")
    .replaceAll("=", "");
}

/* =====================================================
   SECURITY HEADERS (DON’T BLOCK IFRAME IN BB)
===================================================== */
app.use((req, res, next) => {
  // We WANT Blackboard to be able to iframe /launch, so do NOT set X-Frame-Options:DENY/SAMEORIGIN
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("Referrer-Policy", "no-referrer-when-downgrade");

  // Allow the page to be embedded by Blackboard/Learn domains
  // (Adjust if your Learn host differs)
  res.setHeader(
    "Content-Security-Policy",
    [
      "default-src 'self' https: data: blob:",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:",
      "style-src 'self' 'unsafe-inline' https: data: blob:",
      "img-src 'self' https: data: blob:",
      "connect-src 'self' https: wss: data: blob:",
      "frame-src 'self' https: data: blob:",
      `frame-ancestors https://${LEARN_HOST} https://*.blackboard.com https://*.blackboardcdn.com https://*.bbcollab.com`,
    ].join("; ")
  );

  next();
});

/* =====================================================
   IN-MEM STATE STORE (OIDC LOGIN → LAUNCH)
===================================================== */
const stateStore = new Map();
// state -> { nonce, createdAt }
const STATE_TTL_MS = 10 * 60 * 1000;

function putState(state, nonce) {
  stateStore.set(state, { nonce, createdAt: Date.now() });
}

function consumeState(state) {
  const v = stateStore.get(state);
  stateStore.delete(state);
  if (!v) return null;
  if (Date.now() - v.createdAt > STATE_TTL_MS) return null;
  return v;
}

/* =====================================================
   PLATFORM JWKS (VERIFY ID_TOKEN)
===================================================== */
const platformJwks = createRemoteJWKSet(new URL(PLATFORM_JWKS_URL));

/* =====================================================
   ROUTES
===================================================== */

// Quick sanity check
app.get("/health", (req, res) => res.json({ ok: true }));

// Serve JWKS generated by scripts/generate-jwks.mjs at /jwks.json
// (This is already served via express.static, but keeping explicit is fine.)
app.get("/jwks.json", (req, res) => {
  const jwksPath = path.join(__dirname, "public", "jwks.json");
  if (!fs.existsSync(jwksPath)) {
    return res
      .status(500)
      .json({ error: "jwks.json missing. Run: npm run gen:jwks" });
  }
  res.type("application/json").send(fs.readFileSync(jwksPath, "utf-8"));
});

/**
 * LTI 1.3 Login Initiation Endpoint
 * Learn calls this first, then redirects user to PLATFORM_OIDC_AUTH_ENDPOINT.
 */
app.get("/login", (req, res) => {
  const { iss, login_hint, target_link_uri, lti_message_hint, client_id } =
    req.query;

  // Blackboard typically sends iss/login_hint; target_link_uri can be your launch
  if (!iss || !login_hint) {
    return res.status(400).send("Missing iss or login_hint");
  }

  // Use provided target_link_uri if Learn sends it, else default to our launch
  const target = target_link_uri || `${TOOL_BASE_URL}/launch`;

  // Generate state + nonce
  const state = base64url(crypto.randomBytes(16));
  const nonce = base64url(crypto.randomBytes(16));
  putState(state, nonce);

  const params = new URLSearchParams({
    scope: "openid",
    response_type: "id_token",
    response_mode: "form_post",
    prompt: "none",
    client_id: String(client_id || CLIENT_ID),
    redirect_uri: REDIRECT_URI,
    login_hint: String(login_hint),
    nonce,
    state,
  });

  if (lti_message_hint)
    params.set("lti_message_hint", String(lti_message_hint));

  // Some platforms like target_link_uri included (safe to pass)
  params.set("target_link_uri", String(target));

  const redirectUrl = `${PLATFORM_OIDC_AUTH_ENDPOINT}?${params.toString()}`;
  return res.redirect(302, redirectUrl);
});

/**
 * LTI 1.3 Launch Endpoint (redirect_uri)
 * Blackboard posts id_token here.
 */
app.post("/launch", async (req, res) => {
  try {
    const { id_token, state } = req.body || {};
    if (!id_token || !state) {
      return res.status(400).send("Missing id_token or state");
    }

    const st = consumeState(state);
    if (!st) {
      return res.status(400).send("Invalid/expired state");
    }

    // Verify id_token signature + standard claims
    const { payload } = await jwtVerify(id_token, platformJwks, {
      issuer: PLATFORM_ISSUER,
      audience: CLIENT_ID,
    });

    // Verify nonce matches what we generated at /login
    if (payload.nonce !== st.nonce) {
      return res.status(400).send("Nonce mismatch");
    }

    // Decide what to render:
    // - If you only need a “blank” launch, you can just return 200.
    // - Here we show a minimal page that loads your widget (for testing).
    const user = {
      sub: payload.sub,
      name: payload.name || "",
      email: payload.email || "",
    };

    // If you want LTI launch to also show the widget in the launch iframe,
    // this will do it (but NOTE: this is NOT global across Learn pages).
    const widgetScriptTag = NF_WIDGET_SRC
      ? `<script>
          (function(){
            var s1=document.createElement("script"), s0=document.getElementsByTagName("script")[0];
            s1.async=true;
            s1.src=${JSON.stringify(NF_WIDGET_SRC)};
            s1.charset="UTF-8";
            s1.setAttribute("crossorigin","*");
            s1.setAttribute("id","sw-widget");
            s0.parentNode.insertBefore(s1,s0);
          })();
        </script>`
      : "<!-- NF_WIDGET_SRC not set -->";

    res.status(200).type("html").send(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>NF Widget Launch</title>
  <style>
    html, body { height:100%; margin:0; }
    body { background:#000; color:#fff; font-family:system-ui, Arial; }
    .debug { position:fixed; top:10px; left:10px; padding:10px; background:rgba(0,0,0,.6); border:1px solid rgba(255,255,255,.2); border-radius:10px; }
    .muted { opacity:.7; font-size:12px; }
  </style>
</head>
<body>
  <div class="debug">
    <div><b>Launch OK</b></div>
    <div class="muted">sub: ${escapeHtml(user.sub)}</div>
    <div class="muted">name: ${escapeHtml(user.name)}</div>
    <div class="muted">email: ${escapeHtml(user.email)}</div>
    <div class="muted">This page is just for LTI launch testing.</div>
  </div>
  ${widgetScriptTag}
</body>
</html>`);
  } catch (err) {
    console.error("❌ /launch error:", err);
    res
      .status(500)
      .send(`Launch failed: ${escapeHtml(err?.message || String(err))}`);
  }
});

/* =====================================================
   UEF GLOBAL INJECTION SCRIPT
   - This is what you use when you want the widget EVERYWHERE in Learn
   - Your UEF app should point to: https://YOUR_RENDER_DOMAIN/uef/widget.js
===================================================== */
app.get("/uef/widget.js", (req, res) => {
  res.setHeader("Content-Type", "application/javascript; charset=utf-8");

  if (!NF_WIDGET_SRC) {
    return res.send(
      `console.warn("[UEF] NF_WIDGET_SRC is not set; widget not injected.");`
    );
  }

  // Inject NF widget script into the Blackboard page (top-level document)
  // UEF runs this in the Learn page context, so it can attach directly to document.
  return res.send(
    `
(function(){
  try {
    if (document.getElementById("sw-widget")) {
      // already injected
      return;
    }
    var s = document.createElement("script");
    s.async = true;
    s.src = ${JSON.stringify(NF_WIDGET_SRC)};
    s.charset = "UTF-8";
    s.setAttribute("crossorigin","*");
    s.id = "sw-widget";
    (document.head || document.documentElement).appendChild(s);
    console.log("[UEF] NF widget injected:", s.src);
  } catch (e) {
    console.error("[UEF] Failed to inject widget:", e);
  }
})();`.trim()
  );
});

/* =====================================================
   OPTIONAL: LEARN REST TOKEN (CLIENT CREDENTIALS STYLE)
   Only needed if you plan to call Learn REST APIs.
===================================================== */
app.get("/rest/token", async (req, res) => {
  try {
    if (!REST_KEY || !REST_SECRET) {
      return res.status(400).json({ error: "REST_KEY / REST_SECRET not set" });
    }

    // Blackboard Learn REST token endpoint typically:
    // https://{learnHost}/learn/api/public/v1/oauth2/token
    const url = `https://${LEARN_HOST}/learn/api/public/v1/oauth2/token`;

    const body = new URLSearchParams({
      grant_type: "client_credentials",
    });

    const auth = Buffer.from(`${REST_KEY}:${REST_SECRET}`).toString("base64");

    const r = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body,
    });

    const data = await r.json();
    return res.status(r.status).json(data);
  } catch (e) {
    console.error("❌ /rest/token error:", e);
    res.status(500).json({ error: e?.message || String(e) });
  }
});

/* =====================================================
   START
===================================================== */
app.listen(PORT, () => {
  console.log(`✅ Server running on :${PORT}`);
  console.log(`- Health: ${TOOL_BASE_URL}/health`);
  console.log(`- JWKS:   ${TOOL_BASE_URL}/jwks.json`);
  console.log(`- Login:  ${TOOL_BASE_URL}/login`);
  console.log(`- Launch: ${TOOL_BASE_URL}/launch`);
  console.log(`- UEF JS: ${TOOL_BASE_URL}/uef/widget.js`);
});
